# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatroom.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63hatroom.proto\"G\n\tImageData\x12\r\n\x05\x63olor\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"I\n\x1a\x43ustomImageEndpointRequest\x12\x19\n\x05image\x18\x01 \x01(\x0b\x32\n.ImageData\x12\x10\n\x08userName\x18\x02 \x01(\t\"/\n\x1b\x43ustomImageEndpointResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x1a\n\x07Nothing\x12\x0f\n\x07nothing\x18\x01 \x01(\x08\";\n\x12sendMessageRequest\x12\x13\n\x0bsentMessage\x18\x01 \x01(\t\x12\x10\n\x08userName\x18\x02 \x01(\t\"%\n\x11\x63onnectionRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\"&\n\x11\x63onnectionConfirm\x12\x11\n\tconnected\x18\x01 \x01(\x08\"\"\n\x0eonCloseRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\",\n\x14\x64isconnectionConfirm\x12\x14\n\x0c\x64isconnected\x18\x01 \x01(\x08\x32\xda\x02\n\x04\x43hat\x12\x30\n\rmessageStream\x12\x08.Nothing\x1a\x13.sendMessageRequest0\x01\x12,\n\x0bsendMessage\x12\x13.sendMessageRequest\x1a\x08.Nothing\x12\x37\n\rconnectedUser\x12\x12.connectionRequest\x1a\x12.connectionConfirm\x12\x39\n\x0fonDisconnection\x12\x0f.onCloseRequest\x1a\x15.disconnectionConfirm\x12\x36\n\x0bimageStream\x12\x08.Nothing\x1a\x1b.CustomImageEndpointRequest0\x01\x12\x46\n\tsendImage\x12\x1b.CustomImageEndpointRequest\x1a\x1c.CustomImageEndpointResponseB\x02P\x01\x62\x06proto3')



_IMAGEDATA = DESCRIPTOR.message_types_by_name['ImageData']
_CUSTOMIMAGEENDPOINTREQUEST = DESCRIPTOR.message_types_by_name['CustomImageEndpointRequest']
_CUSTOMIMAGEENDPOINTRESPONSE = DESCRIPTOR.message_types_by_name['CustomImageEndpointResponse']
_NOTHING = DESCRIPTOR.message_types_by_name['Nothing']
_SENDMESSAGEREQUEST = DESCRIPTOR.message_types_by_name['sendMessageRequest']
_CONNECTIONREQUEST = DESCRIPTOR.message_types_by_name['connectionRequest']
_CONNECTIONCONFIRM = DESCRIPTOR.message_types_by_name['connectionConfirm']
_ONCLOSEREQUEST = DESCRIPTOR.message_types_by_name['onCloseRequest']
_DISCONNECTIONCONFIRM = DESCRIPTOR.message_types_by_name['disconnectionConfirm']
ImageData = _reflection.GeneratedProtocolMessageType('ImageData', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDATA,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:ImageData)
  })
_sym_db.RegisterMessage(ImageData)

CustomImageEndpointRequest = _reflection.GeneratedProtocolMessageType('CustomImageEndpointRequest', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMIMAGEENDPOINTREQUEST,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:CustomImageEndpointRequest)
  })
_sym_db.RegisterMessage(CustomImageEndpointRequest)

CustomImageEndpointResponse = _reflection.GeneratedProtocolMessageType('CustomImageEndpointResponse', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMIMAGEENDPOINTRESPONSE,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:CustomImageEndpointResponse)
  })
_sym_db.RegisterMessage(CustomImageEndpointResponse)

Nothing = _reflection.GeneratedProtocolMessageType('Nothing', (_message.Message,), {
  'DESCRIPTOR' : _NOTHING,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:Nothing)
  })
_sym_db.RegisterMessage(Nothing)

sendMessageRequest = _reflection.GeneratedProtocolMessageType('sendMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDMESSAGEREQUEST,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:sendMessageRequest)
  })
_sym_db.RegisterMessage(sendMessageRequest)

connectionRequest = _reflection.GeneratedProtocolMessageType('connectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONREQUEST,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:connectionRequest)
  })
_sym_db.RegisterMessage(connectionRequest)

connectionConfirm = _reflection.GeneratedProtocolMessageType('connectionConfirm', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONCONFIRM,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:connectionConfirm)
  })
_sym_db.RegisterMessage(connectionConfirm)

onCloseRequest = _reflection.GeneratedProtocolMessageType('onCloseRequest', (_message.Message,), {
  'DESCRIPTOR' : _ONCLOSEREQUEST,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:onCloseRequest)
  })
_sym_db.RegisterMessage(onCloseRequest)

disconnectionConfirm = _reflection.GeneratedProtocolMessageType('disconnectionConfirm', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTIONCONFIRM,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:disconnectionConfirm)
  })
_sym_db.RegisterMessage(disconnectionConfirm)

_CHAT = DESCRIPTOR.services_by_name['Chat']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _IMAGEDATA._serialized_start=18
  _IMAGEDATA._serialized_end=89
  _CUSTOMIMAGEENDPOINTREQUEST._serialized_start=91
  _CUSTOMIMAGEENDPOINTREQUEST._serialized_end=164
  _CUSTOMIMAGEENDPOINTRESPONSE._serialized_start=166
  _CUSTOMIMAGEENDPOINTRESPONSE._serialized_end=213
  _NOTHING._serialized_start=215
  _NOTHING._serialized_end=241
  _SENDMESSAGEREQUEST._serialized_start=243
  _SENDMESSAGEREQUEST._serialized_end=302
  _CONNECTIONREQUEST._serialized_start=304
  _CONNECTIONREQUEST._serialized_end=341
  _CONNECTIONCONFIRM._serialized_start=343
  _CONNECTIONCONFIRM._serialized_end=381
  _ONCLOSEREQUEST._serialized_start=383
  _ONCLOSEREQUEST._serialized_end=417
  _DISCONNECTIONCONFIRM._serialized_start=419
  _DISCONNECTIONCONFIRM._serialized_end=463
  _CHAT._serialized_start=466
  _CHAT._serialized_end=812
# @@protoc_insertion_point(module_scope)
